-- ----------------------------
-- Table structure for `quests`
-- ----------------------------
DROP TABLE IF EXISTS `quests`;
CREATE TABLE `quests` (
  `QuestID` int(11) NOT NULL DEFAULT '0',
  `QuestName` varchar(200) DEFAULT NULL,
  `MinLVL` int(11) DEFAULT '1',
  `MaxLVL` int(11) DEFAULT '60',
  `isDialog` int(11) DEFAULT '0',
  `text1` varchar(200) NOT NULL DEFAULT 'read this',
  `text2` varchar(200) DEFAULT NULL,
  `text3` varchar(200) DEFAULT NULL,
  `text4` varchar(200) DEFAULT NULL,
  `target1type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target1id` decimal(11,0) NOT NULL DEFAULT '0', -- for target type kill - npc id, for drop - item id, for use item - item id, for use lobby - npc id, for say - npc id.
  `target1count` int(11) NOT NULL DEFAULT '0', 
  `target2type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target2id` decimal(11,0) NOT NULL DEFAULT '0',
  `target2count` int(11) NOT NULL DEFAULT '0',
  `target3type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target3id` decimal(11,0) NOT NULL DEFAULT '0',
  `target3count` int(11) NOT NULL DEFAULT '0',
  `target4type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target4id` decimal(11,0) NOT NULL DEFAULT '0',
  `target4count` int(11) NOT NULL DEFAULT '0',
  `target5type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target5id` decimal(11,0) NOT NULL DEFAULT '0', 
  `target5count` int(11) NOT NULL DEFAULT '0',
  `target6type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target6id` decimal(11,0) NOT NULL DEFAULT '0',
  `target6count` int(11) NOT NULL DEFAULT '0',
  `target7type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target7id` decimal(11,0) NOT NULL DEFAULT '0',
  `target7count` int(11) NOT NULL DEFAULT '0',
  `target8type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target8id` decimal(11,0) NOT NULL DEFAULT '0',
  `target8count` int(11) NOT NULL DEFAULT '0',
  `target9type` enum('KILL','DROP','USE_ITEM','USE_LOBBY','SAY') DEFAULT NULL,
  `target9id` decimal(11,0) NOT NULL DEFAULT '0', 
  `target9count` int(11) NOT NULL DEFAULT '0', 
  `awardXP` int(11) DEFAULT '1',
  `award1type` enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award1count` int(11)  DEFAULT '0',
  `award2type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award2count` int(11)  DEFAULT '0',
  `award3type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award3count` int(11)  DEFAULT '0',
  `award4type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award4count` int(11)  DEFAULT '0',
  `award5type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award5count` int(11)  DEFAULT '0',
  `award6type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award6count` int(11)  DEFAULT '0',
  `award7type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award7count` int(11)  DEFAULT '0',
  `award8type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award8count` int(11)  DEFAULT '0',
  `award9type` enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award9count` int(11)  DEFAULT '0',
  `award10type`  enum('MONEY','ITEM','BUFF','SKILL','STAMINA') DEFAULT NULL,
  `award10count` int(11)  DEFAULT '0',
  `endtext1` varchar(200) NOT NULL DEFAULT 'read this',
  `endtext2` varchar(200) DEFAULT NULL,
  `endtext3` varchar(200) DEFAULT NULL,
  `endtext4` varchar(200) DEFAULT NULL,
  
  PRIMARY KEY (`QuestID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;